<a href="https://colab.research.google.com/github/aminufolashade/AI-Based-ChatBot/blob/main/intro_python_rbs_oct25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
b6 = "a"
c6 = 5

In [ ]:
print(b6 * c6)

aaaaa

In [ ]:
height = [1, 2, 3]
weight = [1, 2, 3]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
sum(height)

6

In [ ]:
'hello world'

'hello world'

# Entering Data into Python

Write text in Python

In [ ]:
class_rep_name = "Musa" # string

In [ ]:
age = 15 # numerical variable (integer)

In [ ]:
weight = 93.90 # numerical variable (float)

In [ ]:
type(age)

int

Type Casting (Conversion)

In [ ]:
str_age = str(age)

In [ ]:
print(str_age)

15

In [ ]:
type(str_age)

str

In [ ]:
str_weight = str(weight)

In [ ]:
print(type(str_weight))

<class 'str'>

In [ ]:
str_weight

'93.9'

Special Characters/Operators

In [ ]:
# + - ** %

In [ ]:
print(1 + 1)

2

In [ ]:
print(1 * 1)

1

In [ ]:
print(3 ** 2)

9

In [ ]:
print(3 / 2)

1.5

In [ ]:
print(5 // 2)

1

In [ ]:
print(3 % 2)

1

In [ ]:
name_one = 'Ada'

In [ ]:
name_two = 'Musa'

In [ ]:
print(name_one + name_two)

AdaMusa

In [ ]:
print(name_one * 4)

AdaAdaAdaAda

In [ ]:
# Boolean Types - True/False

age = 10
has_pen = True

In [ ]:
type(has_pen)

bool

In [ ]:
#  Operator Precedence - Python follows BODMAS
print(2 + (3 * 4))

14

Working with strings

In [ ]:
# String methods - a special class of functions that work on a string type variable
name_one.lower()

'ada'

In [ ]:
name_one.upper()

'ADA'

In [ ]:
name_one.capitalize()

'Ada'

In [ ]:
name_one.count('A')

1

In [ ]:
name_one.islower()

False

In [ ]:
spaced_name = " Ada "
space_name_right = "Ada "
space_name_left = " Ada"

In [ ]:
# print length of spaced name after stripping blank spaces
print(len(spaced_name.strip()))

3

In [ ]:
print(len(spaced_name))

5

In [ ]:
print(space_name_left.lstrip())

Ada

In [ ]:
print(space_name_left.rstrip())

 Ada

In [ ]:
print(len(space_name_left.lstrip()))

3

In [ ]:
name_one.find('d')

1

In [ ]:
name_one.startswith('a')

False

In [ ]:
# start:stop:stride/step - in python, anytime you want to slide, please use a square bracket

name_one[0:2]

'Ad'

In [ ]:
name_three = 'Olayinka'

In [ ]:
name_three[1:5].capitalize().upper()

'LAYI'

In [ ]:
name_three[0:6:2]

'Oai'

In [ ]:
name_three[:5:2]

'Oai'

In [ ]:
name_three[-2:]

'ka'

In [ ]:
fruits = "apple, banana, cherry"

In [ ]:
fruits.split(",")

['apple', ' banana', ' cherry']

In [ ]:
age = 16

## Collections

In [ ]:
# major on Four different collections in Python

In [ ]:
# List (square brackets always)

height = [1,2,3]

In [ ]:
# List slicing

sum(height[0:2])

3

In [ ]:
print(height[0] + height[1])

3

In [ ]:
# List methoda

height.append(4)

In [ ]:
height

[1, 2, 3, 4]

In [ ]:
height.count(1)

1

In [ ]:
height.sort()

In [ ]:
height

[1, 2, 3, 4]

In [ ]:
height.pop()

4

In [ ]:
height

[1, 2, 3]

In [ ]:
type(height)

list

In [ ]:
# Tuple ( ) Use parenthesis - immutable

In [ ]:
age = (16, 16, 25, 30)

In [ ]:
type(age)

tuple

In [ ]:
# Sets { } Curly Braces - Does not allow duplicates

In [ ]:
id = {1, 2, 3, 4}

In [ ]:
type(id)

set

In [ ]:
id_dup = {1, 1, 2, 2, 3, 3}

In [ ]:
id_dup

{1, 2, 3}

In [ ]:
# Dictionaries { } Curly Braces - Requires Header Name (i.e key)

In [ ]:
id_column = {'id': [1, 2, 3, 4]}

In [ ]:
type(id_column)

dict

In [ ]:
print(id_column)

{'id': [1, 2, 3, 4]}

In [ ]:
dataset = {
    'id': [1, 2, 3, 4],
    'age': [16, 16, 25, 30],
    'height': [1, 2, 3, 4],
    'weight': [1, 2, 3, 4]
}

In [ ]:
print(dataset)

{'id': [1, 2, 3, 4], 'age': [16, 16, 25, 30], 'height': [1, 2, 3, 4], 'weight': [1, 2, 3, 4]}

In [ ]:
print(type(dataset))

<class 'dict'>

In [ ]:
import pandas

dataframe = pandas.DataFrame(dataset)
dataframe

   id  age  height  weight
0   1   16       1       1
1   2   16       2       2
2   3   25       3       3
3   4   30       4       4

In [ ]:
import pandas as p

dataframe = p.DataFrame(dataset)
dataframe

   id  age  height  weight
0   1   16       1       1
1   2   16       2       2
2   3   25       3       3
3   4   30       4       4

String I/O (Input - Output)

In [ ]:
# Input - using the input() function

In [ ]:
my_name = input('What is your name?')

What is your name?James

In [ ]:
my_name

'James'

In [ ]:
my_age = int(input('What is your age?'))

What is your age?16

In [ ]:
type(my_age)

int

In [ ]:
exam_score = 95.9997

In [ ]:
h_w_ratio = 0.8

In [ ]:
# String Output - F-string (variable-interpolation capable)

In [ ]:
print(f'My name is {my_name} and I am {my_age} years old.')

My name is James and I am 16 years old.

In [ ]:
print(f'My name is {my_name} and I am {my_age} years old. I scored {exam_score: .2f} in the exam. My h_w_ratio is{h_w_ratio: .0%}')

My name is James and I am 16 years old. I scored  96.00 in the exam. My h_w_ratio is 80%

In [ ]:
print(f'My name is {my_name} and I am {my_age} years old. I scored {exam_score: .4f} in the exam. My h_w_ratio is{h_w_ratio: .2%}')

My name is James and I am 16 years old. I scored  95.9997 in the exam. My h_w_ratio is 80.00%